version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '20:00'
    timezone: Europe/Minsk
  open-pull-requests-limit: 10
  reviewers:
  - astrophena
  assignees:
  - astrophena
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: '20:00'
    timezone: Europe/Minsk
  open-pull-requests-limit: 10
  reviewers:
  - astrophena
  assignees:
  - astrophena
