// © 2020 Ilya Mateyko. All rights reserved.
// Use of this source code is governed by the MIT
// license that can be found in the LICENSE.md file.

// Package version contains a version of gen.
package version

import (
	"runtime/debug"
	"strings"
)

const defaultVersion = "devel"

// Version is generated by `make`, `goreleaser` or extracted from debug.BuildInfo.
var Version = defaultVersion

func init() {
	if Version == defaultVersion {
		bi, ok := debug.ReadBuildInfo()
		if ok {
			Version = strings.TrimPrefix(bi.Main.Version, "v")
		}
	}
}
