project_name: gen
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    # Keep these synced with Makefile.
    flags:
      - -trimpath
    ldflags:
      - -s -w -X go.astrophena.name/gen/version.Version={{.Version}} -buildid=
archives:
  - format: binary
nfpms:
  - package_name: gen
    vendor: Ilya Mateyko
    homepage: https://github.com/astrophena/gen
    maintainer: Ilya Mateyko <me@astrophena.name>
    description: An another static site generator.
    license: MIT
    formats:
      - deb
    contents:
      - src: completions/completion.bash
        dst: /usr/share/bash-completion/completions/gen
      - src: completions/completion.zsh
        dst: /usr/share/zsh/vendor-completions/_gen
    bindir: /usr/bin
checksum:
  name_template: 'checksums.txt'
snapshot:
  # Keep this synced with Makefile.
  name_template: "{{ .Tag }}-next"
