project_name: gen
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/gen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    # Keep these synced with Makefile.
    flags:
      - -trimpath
    ldflags:
      - -s -w -X astrophena.me/gen/internal/buildinfo.Version={{.Version}} -buildid=
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  # Keep this synced with Makefile.
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
