project_name: gen
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    # Keep these synced with Makefile.
    flags:
      - -trimpath
    ldflags:
      - -s -w -X go.astrophena.me/gen/internal/version.Version={{.Version}} -buildid=
archives:
  - format: binary
nfpms:
  - package_name: gen
    vendor: Ilya Mateyko
    homepage: https://go.astrophena.me/gen
    maintainer: Ilya Mateyko <me@astrophena.me>
    description: An another static site generator.
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
checksum:
  name_template: 'checksums.txt'
snapshot:
  # Keep this synced with Makefile.
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
