project_name: gen
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    # Keep these synced with Makefile.
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -buildid=
scoop:
  bucket:
    owner: astrophena
    name: gen
  commit_author:
    name: Ilya Mateyko
    email: git@inbox.astrophena.me
  homepage: "https://github.com/astrophena/site"
  description: "An another static site generator."
  license: MIT
archives:
  - format: tar.gz
checksum:
  name_template: 'checksums.txt'
snapshot:
  # Keep this synced with Makefile.
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"
changelog:
  skip: true
