name: Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
jobs:
  tests:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: make
      - name: Test
        run: make test
