# © 2020 Ilya Mateyko. All rights reserved.
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE.md file.

name: Tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2.3.1
      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        id: build
        run: make
      - name: Run tests
        id: run-tests
        run: make test
      - name: Test site creation
        id: test-site-creation
        run: |
          ./gen new example
          cd example
          ../gen build
        shell: bash
