name: Tests
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Build
        id: build
        run: make
      - name: Run tests
        id: run-tests
        run: make test
